// ListOfOrchids.js - Data storage for orchid collection
export const ListOfOrchids = [
  {
    Id: 1,
    name: 'Taichung Beauty',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://barritaorchids.com/cdn/shop/products/Cf592_1024x1024.jpg',
    color: 'pink',
    numberOfLike: 192,
    origin: 'Taiwan',
    category: 'Cattleya',
    theme: 'tet',
    description: 'The Taichung Beauty is a stunning Cattleya hybrid from Taiwan. Known for its vibrant pink petals and exceptional fragrance, this orchid is perfect for Lunar New Year celebrations. It blooms in early spring and can last up to 6 weeks with proper care.',
    price: 45.99,
    careLevel: 'Intermediate',
  },
  {
    Id: 2,
    name: 'Miss Saigon',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    color: 'yellow',
    numberOfLike: 150,
    origin: 'Vietnam',
    category: 'Dendrobium',
    theme: 'women',
    description: 'A beautiful yellow Dendrobium native to Vietnam. Perfect for International Women\'s Day (March 8th). Its cheerful yellow blooms symbolize friendship and new beginnings. This orchid thrives in warm, humid environments.',
    price: 32.99,
    careLevel: 'Easy',
  },
  {
    Id: 3,
    name: 'Purple Passion',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?w=800',
    color: 'purple',
    numberOfLike: 289,
    origin: 'Thailand',
    category: 'Phalaenopsis',
    theme: 'teacher',
    description: 'An exquisite purple Phalaenopsis from Thailand, ideal for Vietnamese Teachers\' Day (November 20th). The deep purple color represents respect and admiration. This orchid blooms for 2-3 months and is relatively easy to care for.',
    price: 52.99,
    careLevel: 'Easy',
  },
  {
    Id: 4,
    name: 'White Elegance',
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image: 'https://images.unsplash.com/photo-1584589167171-541ce45f1eea?w=800',
    color: 'white',
    numberOfLike: 315,
    origin: 'Japan',
    category: 'Phalaenopsis',
    theme: 'tet',
    description: 'Pure white Phalaenopsis orchid from Japan. Symbolizes purity and prosperity, making it perfect for Lunar New Year. This natural variety is highly sought after for its pristine white blooms and elegant appearance.',
    price: 58.99,
    careLevel: 'Intermediate',
  },
  {
    Id: 5,
    name: 'Golden Sunrise',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
    color: 'orange',
    numberOfLike: 178,
    origin: 'Brazil',
    category: 'Cattleya',
    theme: 'tet',
    description: 'Vibrant orange Cattleya from Brazil. The golden-orange hue represents wealth and good fortune, perfect for Tet celebrations. This natural species brings warmth and energy to any space.',
    price: 38.99,
    careLevel: 'Intermediate',
  },
  {
    Id: 6,
    name: 'Blue Moon',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://product.hstatic.net/200000708755/product/hoa-hong-blue-moonstone-kobetaroses2_ef2788b1a3b6485dad4d99f9fcf6df2b_master.png',
    color: 'blue',
    numberOfLike: 421,
    origin: 'Netherlands',
    category: 'Vanda',
    theme: 'women',
    description: 'Rare blue Vanda orchid from the Netherlands. This spectacular hybrid is perfect for Women\'s Day gifts. The unique blue color is achieved through special breeding techniques. A true showstopper in any collection.',
    price: 75.99,
    careLevel: 'Advanced',
  },
  {
    Id: 7,
    name: 'Pink Princess',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=800',
    color: 'pink',
    numberOfLike: 267,
    origin: 'Malaysia',
    category: 'Dendrobium',
    theme: 'women',
    description: 'Delicate pink Dendrobium from Malaysia. Perfect for celebrating special women in your life. This natural variety is easy to care for and produces abundant blooms throughout the year.',
    price: 29.99,
    careLevel: 'Easy',
  },
  {
    Id: 8,
    name: 'Sunset Glory',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=800',
    color: 'red',
    numberOfLike: 356,
    origin: 'Singapore',
    category: 'Vanda',
    theme: 'women',
    description: 'Stunning red Vanda hybrid from Singapore. The deep red color symbolizes love and passion, making it an ideal gift for Women\'s Day. This orchid requires bright light and high humidity.',
    price: 68.99,
    careLevel: 'Advanced',
  },
  {
    Id: 9,
    name: 'Lavender Dream',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://bazantravel.com/cdn/medias/uploads/51/51415-hoa-lavender-da-lat-700x525.jpg',
    color: 'lavender',
    numberOfLike: 198,
    origin: 'Australia',
    category: 'Cattleya',
    theme: 'teacher',
    description: 'Soft lavender Cattleya from Australia. Perfect for honoring teachers on November 20th. The gentle color and sweet fragrance make it a thoughtful and elegant gift. Blooms twice a year with proper care.',
    price: 42.99,
    careLevel: 'Intermediate',
  },
];

export default ListOfOrchids;
